# Generated by Django 6.0 on 2025-12-12 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_otp'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='otp',
            new_name='core_otp_email_d53edf_idx',
            old_name='core_otp_email_7ae5f1_idx',
        ),
    ]
