# Generated by Django 6.0 on 2025-12-12 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_movie_video_url'),
        ('core', '0005_rename_core_otp_email_7ae5f1_idx_core_otp_email_d53edf_idx'),
    ]

    operations = [
    ]
