# Generated by Django 6.0 on 2025-12-15 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='original_detail_url',
            field=models.URLField(blank=True, help_text='Original source URL from 1flix.to (e.g., https://1flix.to/watch-movie/...)', max_length=1000, null=True),
        ),
    ]
